
parameters:
  - name: job
    type: string
    default: All

resources:
  repositories:
    - repository: templates
      type: git
      name: templates
      ref: refs/heads/main

stages:
  - template: build-and-test.yml@templates
    parameters:
      buildConfiguration: Debug
      runTests: true
      ${{ if eq(parameters.job, 'All') }}:
        jobOrder: 
          - name: FleetNativeAPIChecks
          - name: FleetNativeAPIChecks1
