trigger:
  branches:
    include:
      - main
      - releases/*
    exclude:
      - uat
  tags:
    include:
      - v2.*
    exclude:
      - v5.0

pr:
  branches:
    include:
    - current
    - main
    exclude:
      - uat

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Running pipeline with specific build strategy
  displayName: 'pipeline run'
