trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
- name: repoparam123
  type: string
  default: reponame
- name: branchparam
  type: string
  default: main

variables:
  - name: repositoryvar
    value: ${{parameters.repoparam123}}
  - name: branchvar
    value: ${{parameters.branchparam}}


resources:
  repositories:
    - repository: gitrepo
      type: github
      name: Jiancao164/cs5001-test
      ref: $(branchvar)
      endpoint: Jiancao164

steps:
- checkout: gitrepo
  displayName: download repository
