trigger:
- none

pr: none 

pool:
  vmImage: windows-latest



steps:
- checkout: self
  displayName: Download self repo
  path: "s/Source"



- task: UseDotNet@2
  displayName: download .NET 6
  inputs:
    packageType: sdk
    version: '6.0.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)/projects/ClassLibrary/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  displayName: build Class Library project and create Nuget package
  inputs:
    solution: '$(Build.SourcesDirectory)/projects/ClassLibrary/*.sln'
    msbuildArguments: '/p:Configuration=Debug /p:Platform="Any CPU"'


- task: NuGetAuthenticate@1
  displayName: nuget authenticate


- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.SourcesDirectory)/projects/ClassLibrary/bin/Debug/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '8184ae86-a38d-4131-b509-d9c780e1f2a2/01f1a152-37bb-420a-b16e-8f3b058aad70'
    allowPackageConflicts: true

