trigger:
- none

pool:
  vmImage: ubuntu-latest
stages:
- stage: stage1
  displayName: display name for your stage1
  jobs:
  - job: job1
    displayName: display name for job1
    steps:
    - script: echo job1.task1
      displayName: running job1.task1
  - job: job2
    displayName: display name for job2
    steps:
    - script: echo job2.task1
      displayName: running job2.task1

- stage: stage2
  displayName: display name for your stage2
  jobs:
  - job: job3
    displayName: display name for job3
    steps:
    - script: echo job3.task3
      displayName: running job3.task3
  - job: job4
    displayName: display name for job4
    steps:
    - script: echo job4.task4
      displayName: running job4.task4